junya30st/freemarket_sample_61e

- Gemfile
- app/assets/javascripts/application.js
gem導入
・devise
・haml-rails
・jquery-rails
application.jsの追記
ユーザー管理機能、haml書き換え、jquery使用の為
> gem-devise.haml.jquery

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
#why
・デプロイ環境設定のため
・アイコン使用のため
・テスト環境実装のため
#what
各種gemの追加
・pry-rails
・rspec
・capistrano
・font-awesome
・unicorn
> gemadd_pryrails_rspec_capistrano_font-awesome_unicorn

- config/unicorn.rb
#what
unicorn.rbファイルの追加
#why
アプリケーションサーバの設定、外部からコマンド制御するため
> add unicorn.rb

- config/database.yml
#why
MySqlのソケットエラーを解決するため
#what
本番環境のsocketファイルのパスを修正
> database.yml_socket

- Capfile
- config/deploy.rb
- config/deploy/production.rb
- config/environments/production.rb
- config/unicorn.rb
#what
自動デプロイ実装のための設定ファイルの編集
#why
作業効率向上の為
> Capistrano-setting

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/_identification.scss
- app/controllers/users_controller.rb
- app/views/users/identification.html.haml
- config/routes.rb
メルカリの本人登録情報フロント実装
フロント実装が終わりましたので、コードレビュー願います
> [mercari]本人登録情報フロント実装

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/modules/_items.scss
- app/controllers/items_controller.rb
- app/views/items/new.html.haml
- app/views/shared/_exhibit-btn.html.haml
- config/environments/development.rb
- config/environments/production.rb
- config/routes.rb
- config/storage.yml
- db/migrate/20191107111719_create_active_storage_tables.active_storage.rb
- db/migrate/20191107112424_add_column_items.rb
- db/schema.rb
#what
・商品出品ページの情報がテーブルに保存される
・選択した画像がS3にアップロードされる
・ActiveStorage導入
#why
・商品を出品し、情報を後から活用するため
・画像アップロードのテスト
> TableCreate & S3 upload

- app/models/comment.rb
- app/models/like.rb
- app/models/offer.rb
- app/models/point.rb
- app/models/transaction.rb
- db/migrate/20191108105555_create_transactions.rb
- db/migrate/20191108105638_create_offers.rb
- db/migrate/20191108105645_create_points.rb
- db/migrate/20191108105651_create_comments.rb
- db/migrate/20191108105657_create_likes.rb
- db/schema.rb
- spec/factories/comments.rb
- spec/factories/likes.rb
- spec/factories/offers.rb
- spec/factories/points.rb
- spec/factories/transactions.rb
- spec/models/comment_spec.rb
- spec/models/like_spec.rb
- spec/models/offer_spec.rb
- spec/models/point_spec.rb
- spec/models/transaction_spec.rb
#what
transactionモデルとテーブルの作成
offerモデルとテーブルの作成
pointモデルとテーブルの作成
commentモデルとテーブルの作成
likeモデルとテーブルの作成
#why
商品購入のロジック作成のため必要なテーブルを作成
> DB_table_create

- app/views/users/identification.html.haml
メルカリの本人情報登録ページの都道府県名挿入の件
追加実装できましたので、リクエストします
> [本人情報登録ページ]都道府県名挿入

- README.md
- app/assets/javascripts/cards.coffee
- app/assets/javascripts/image.js
- app/assets/javascripts/signin.coffee
- app/assets/javascripts/signup.coffee
- app/assets/stylesheets/cards.scss
- app/assets/stylesheets/config/_yender.scss
- app/assets/stylesheets/modules/_sell.scss
- app/assets/stylesheets/signin.scss
- app/assets/stylesheets/signup.scss
- app/controllers/items_controller.rb
- app/models/item.rb
- app/models/user.rb
- app/views/items/new.html.haml
#what
商品出品する際、アップロードした画像のプレビューを作成
選択画像のリセット機能を実装
#why
登録するイメージを確認するため
> itemUpload_javascript

- app/controllers/items_controller.rb
- app/views/items/show.html.haml
- db/migrate/20191110080938_remove_status_from_items.rb
- db/migrate/20191110082231_add_status_to_items.rb
- db/schema.rb
#what
enumで参照するデータをinteger型に修正
#why
商品詳細ページで登録データを参照するため
本番環境でのトラブルを事前に防ぐため早い段階でマージ
> itemDBupdate

- app/assets/stylesheets/modules/_items.scss
- app/views/items/index.html.haml
- app/views/items/show.html.haml
- app/views/shared/_header-sp.html.haml
- app/views/users/identification.html.haml
- app/views/users/logout.html.haml
- app/views/users/mypage.html.haml
- app/views/users/profile.html.haml
- config/breadcrumbs.rb
- config/routes.rb
パンくずに適合するヘッダーを作成した。
ログイン/ログアウトのパスを一部ページに追記した。
cssの細かい修正をした。
ログインおよびログアウトによってヘッダー部が変化するか確認するため。
> パンくずに適合するヘッダーの作成およびパスの設定

- app/assets/javascripts/items-show.js
- app/assets/stylesheets/mixin/_index-mixin.scss
- app/assets/stylesheets/modules/_items.scss
- app/assets/stylesheets/modules/_show.scss
- app/views/items/_item.html.haml
- app/views/items/show.html.haml
- app/views/users/identification.html.haml
- app/views/users/logout.html.haml
- app/views/users/mypage.html.haml
- app/views/users/profile.html.haml
- config/environments/development.rb
出品した商品の情報のうち、商品画像をviewへ反映できるようにした。
写真の切り替えができるようにした。
細かいcssの修正。
出品した商品の画像を見れるようにするため。
https://gyazo.com/cf99ff47c693464ca9ba7e2bbd6df506
> 出品商品情報のフロントへの反映

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_yender.scss
- app/assets/stylesheets/modules/_flash.scss
- app/assets/stylesheets/modules/_myitems.scss
- app/controllers/items_controller.rb
- app/controllers/myitems_controller.rb
- app/helpers/myitems_helper.rb
- app/views/items/show.html.haml
- app/views/layouts/_notifications.html.haml
- app/views/layouts/application.html.haml
- app/views/myitems/edit.html.haml
- app/views/myitems/show.html.haml
- config/application.rb
- config/environments/development.rb
- config/locales/devise.ja.yml
- config/locales/ja.yml
- config/routes.rb
- spec/controllers/myitems_controller_spec.rb
- spec/helpers/myitems_helper_spec.rb
#what
ユーザーが出品した商品の詳細ページ表示機能を追加
出品後には詳細ページへリダイレクトするようにコントローラーを修正
出品した商品の削除機能の追加
#why
出品した商品を確認・編集するため
> 商品詳細ページの実装および削除機能の追加

- app/assets/javascripts/edit-image.js
- app/assets/javascripts/image.js
- app/assets/stylesheets/modules/_myitems.scss
- app/assets/stylesheets/modules/_sell.scss
- app/controllers/items_controller.rb
- app/controllers/myitems_controller.rb
- app/helpers/items_helper.rb
- app/views/items/edit.html.haml
- app/views/myitems/show.html.haml
- config/routes.rb
#what
入力済みの情報をデフォルトで表示する
内容変更したものがDBに反映される
画像の追加・削除機能の実装
#why
出品した商品の情報を編集するため
> 商品編集ページの機能実装

- app/controllers/signup_controller.rb
signupコントローラ内の動作説明の追加。
会員登録時のパスワード自動生成文の追加。
メンバー内での共有のため。
会員登録時のエラー解決のため。
> 動作説明の追加とパス生成文の追加

- app/assets/stylesheets/modules/_schiation.scss
- app/controllers/items_controller.rb
- app/controllers/signup_controller.rb
- app/controllers/users_controller.rb
- app/views/shared/_header-sp.html.haml
- app/views/shared/_header.html.haml
- app/views/shared/_mypage-nav.html.haml
- app/views/users/completed.html.haml
- app/views/users/in_progress.html.haml
- app/views/users/listing.html.haml
自分が出品した商品を一覧で表示できるようにした。
出品中の商品それぞれの状況を把握し易くするため。
> 出品商品一覧表示機能の実装

- app/assets/stylesheets/modules/_signin.scss
- app/assets/stylesheets/modules/_signup-process.scss
- app/views/cards/edit.html.haml
- app/views/cards/edit1.html.haml
- app/views/cards/show.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/shared/_bottombar.html.haml
- app/views/signup/done.html.haml
> トップページ / サインインぺージのビュー修正

- app/assets/javascripts/mypage.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mixin/_mypage-mixin.scss
- app/assets/stylesheets/modules/_likes.scss
- app/assets/stylesheets/modules/_schiation.scss
- app/assets/stylesheets/modules/_show.scss
- app/controllers/items_controller.rb
- app/controllers/likes_controller.rb
- app/helpers/likes_helper.rb
- app/models/like.rb
- app/views/items/searched.html.haml
- app/views/likes/index.html.haml
- app/views/shared/_header-sp.html.haml
- app/views/shared/_header.html.haml
- app/views/shared/_mypage-nav.html.haml
- app/views/users/listing.html.haml
- config/routes.rb
- spec/controllers/likes_controller_spec.rb
- spec/helpers/likes_helper_spec.rb
いいね！一覧のフロントを作成した。
トップページの商品一覧に自分が出品した商品を表示しないようにした。
検索結果一覧に自分が出品した商品を表示しないようにした。
出品中の商品一覧に出品日および最終更新日を記載するようにした。
cssの細かい修正をした。
トップページにおいて、少しでも目に入る商品を増やすため。
出品中の商品一覧に出品日および最終更新日を記載することにより、出品者が売るための対策を立てやすいと思うから。
> いいね！一覧のフロント作成

- app/assets/javascripts/like.js
- app/assets/stylesheets/modules/_show.scss
- app/controllers/items_controller.rb
- app/views/items/_item.html.haml
- app/views/items/index.html.haml
- app/views/items/show.html.haml
いいねボタンを押すと、プルプル動くようにモーションを追加した。
トップページの商品一覧において、出品中および取引中の商品のみ表示するようにしたと同時に、取引中の商品にはSOLDのタグが写真の左上に表示されるようにした。
サーバーサイドに入るに当たって、発火していることを可視化するため。
https://gyazo.com/1cf3d5de2911afed4257eb9cf5f5b06c
> いいねボタンにおけるモーションの追加

- app/assets/javascripts/mypage.js
- app/assets/stylesheets/modules/_mypage.scss
- app/controllers/items_controller.rb
- app/views/items/_another.html.haml
- app/views/items/_notice-dropdwn.html.haml
- app/views/items/index.html.haml
- app/views/shared/_mypage-nav.html.haml
- app/views/users/mypage.html.haml
マイページのパスやお知らせ部分を修正した。
トップページにアイテムをランダムで表示するようにした。
トップページの見栄えを良くするため。
> マイページの修正およびトップページのランダム表示機能の追加

- app/assets/stylesheets/modules/_signup-process.scss
- app/assets/stylesheets/modules/_signup.scss
- app/controllers/signup_controller.rb
- app/views/signup/done.html.haml
- app/views/signup/signup.html.haml
- app/views/signup/signup1.html.haml
- app/views/signup/signup2.html.haml
- app/views/signup/signup3.html.haml
- app/views/signup/signup4.html.haml
ビューの修正 / sns認証・新規登録・signinの修正
見映えのを良くするため。機能不具合の改善の為。
> ビューの修正 / sns認証・新規登録・signinの修正

- app/assets/stylesheets/modules/_myitems.scss
- app/assets/stylesheets/modules/_signup.scss
- app/views/myitems/show.html.haml
#what
マージによるビューの崩れを修正
#why
本番環境での確認のため
> マージによるビューの崩れを修正

- app/assets/stylesheets/modules/_purchase.scss
- app/views/items/show.html.haml
- app/views/transactions/new.html.haml
> ビューの崩れの修正・ダミー情報の修正

- app/controllers/items_controller.rb
検索機能において、商品名だけでなく商品説明文も検索ワードのヒット対象に追加した。
検索機能をより使いやすくするため。
> 検索機能のアップデート

- app/views/signup/signup3.html.haml
ユーザー新規登録時における発送元情報登録時の名前入力フォームに、ユーザーの名前を設置した。
利便性向上のため。
> 発送元情報登録時の名前入力
